### ISSUE TITLE
Directory probleme

### ISSUE THREAD

**Issue by meditant** [Shubhamvis98/hijacker#9]
In the install script the install directory is install_dir='/usr/lib/hijacker'
but in the python script and hijacker in /usr/bin is /usr/lib/in.fossfrog.hijacker

Best

**Comment by Shubhamvis98** [comment]
Don't use the repository to install the app. Always install from apt. Please check https://fossfrog.in/repo/

**Comment by Shubhamvis98** [comment]
@meditant i've updated the script. But i recommend to install my apps from my deb repository as i mentioned above.
Thanks
